name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v1
      with:
        depth: 1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@preview
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle --jobs 4 --retry 3 --without production
    - name: Run tests
      run: bundle exec rake test
